baseURL = ""
locale = "en-us"
title = "Data Journals Dashboard"
theme = "djd"
DataDir = "hugo-data"

[params]
  description = "Search and filter data journals by type, publisher, APC, and more"
  author = { name = "Thomas Schmidt", email = "thomas.schmidt@uni-mannheim.de" }
  version = "v2026-05-19"

[taxonomies]
  data_journal_type = "data_journal_type"
  publisher = "publisher"
  keywords = "keywords"
  research_fields = "research_fields"
  license_types = "license_types"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[markup]
  [markup.highlight]
    style = "github"
